/**
 * 模块：反向代理管理 — 业务逻辑层
 * 功能：规则 CRUD、nginx vhost 配置生成、HTTPS 自签证书、WebSocket 透传、访问日志
 */
import { randomUUID } from 'node:crypto';
import { AppError } from '../../common/app-error.js';
import { executeCommandStrict } from '../../system/command-executor.js';
import {
  getCertStatus,
  generateSelfSignedCert,
  type CertInfo,
  type CertStatus,
} from '../../system/tls.js';
import * as dao from './proxy.dao.js';
import type {
  ProxyRule,
  CreateProxyRuleInput,
  UpdateProxyRuleInput,
  ProxyCertInfo,
  GenerateCertInput,
  ReloadResult,
  ProxyStatus,
} from './proxy.types.js';

/* ---------- 校验工具 ---------- */

/** 校验 target 格式：IP:Port 或 hostname:Port */
function validateTarget(target: string): void {
  const match = target.match(
    /^([a-zA-Z0-9._-]+|\[[\da-fA-F:]+]):(\d{1,5})$/,
  );
  if (!match) {
    throw AppError.badRequest(
      'INVALID_TARGET',
      `后端目标格式非法: ${target}，应为 IP:Port 或 hostname:Port`,
    );
  }
  const port = parseInt(match[2] ?? '0', 10);
  if (port < 1 || port > 65535) {
    throw AppError.badRequest(
      'INVALID_TARGET',
      `端口超出范围: ${port}`,
    );
  }
}

/** 校验域名格式 */
function validateDomain(domain: string): void {
  if (!domain || domain.trim() === '') {
    throw AppError.badRequest('INVALID_DOMAIN', '域名不能为空');
  }
  // 允许通配符 *.example.com 和普通域名/IP
  const valid =
    /^(\*\.)?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)*[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(
      domain,
    ) ||
    /^(\d{1,3}\.){3}\d{1,3}$/.test(domain) ||
    domain === '_';
  if (!valid) {
    throw AppError.badRequest(
      'INVALID_DOMAIN',
      `域名格式非法: ${domain}`,
    );
  }
}

/** 校验路径格式 */
function validatePath(path: string): void {
  if (!path.startsWith('/')) {
    throw AppError.badRequest(
      'INVALID_PATH',
      `路径必须以 / 开头: ${path}`,
    );
  }
}

/** 规则 ID → vhost 配置文件名 */
function vhostFilename(ruleId: string): string {
  return `${ruleId}.conf`;
}

/* ---------- nginx 配置生成 ---------- */

/**
 * 为单条规则生成 nginx vhost 配置内容
 * 支持：HTTP/HTTPS、WebSocket 透传、访问日志
 */
export function generateVhostConfig(rule: ProxyRule): string {
  const lines: string[] = [];
  const logName = rule.accessLog ? `proxy_${rule.id}` : 'off';
  const upstream = rule.target;

  // HTTP server（80 端口）
  lines.push(`# Auto-generated by Vibe OS proxy module — rule: ${rule.name}`);
  lines.push(`server {`);
  lines.push(`    listen 80;`);
  lines.push(`    server_name ${rule.domain};`);
  lines.push('');

  if (rule.https) {
    // HTTPS 规则：80 端口重定向到 443
    lines.push(`    # HTTPS redirect`);
    lines.push(`    return 301 https://$host$request_uri;`);
    lines.push(`}`);
    lines.push('');

    // HTTPS server（443 端口）
    lines.push(`server {`);
    lines.push(`    listen 443 ssl;`);
    lines.push(`    server_name ${rule.domain};`);
    lines.push('');
    lines.push(`    ssl_certificate ${dao.CERT_PATH};`);
    lines.push(`    ssl_certificate_key ${dao.KEY_PATH};`);
    lines.push(`    ssl_protocols TLSv1.2 TLSv1.3;`);
    lines.push(`    ssl_ciphers HIGH:!aNULL:!MD5;`);
    lines.push('');
  }

  // 访问日志
  if (rule.accessLog) {
    lines.push(`    access_log ${dao.NGINX_LOG_DIR}/${logName}.access.log;`);
    lines.push(`    error_log ${dao.NGINX_LOG_DIR}/${logName}.error.log;`);
  } else {
    lines.push(`    access_log off;`);
  }
  lines.push('');

  // location 块
  lines.push(`    location ${rule.path} {`);
  lines.push(`        proxy_pass http://${upstream};`);
  lines.push(`        proxy_set_header Host $host;`);
  lines.push(`        proxy_set_header X-Real-IP $remote_addr;`);
  lines.push(`        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
  lines.push(`        proxy_set_header X-Forwarded-Proto $scheme;`);

  // WebSocket 透传
  if (rule.websocket) {
    lines.push('');
    lines.push(`        # WebSocket 透传`);
    lines.push(`        proxy_http_version 1.1;`);
    lines.push(`        proxy_set_header Upgrade $http_upgrade;`);
    lines.push(`        proxy_set_header Connection "upgrade";`);
    lines.push(`        proxy_read_timeout 86400s;`);
    lines.push(`        proxy_send_timeout 86400s;`);
  }

  lines.push(`    }`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

/**
 * 为所有启用规则重新生成全部 vhost 配置文件
 * @returns 生成的配置文件数
 */
export async function generateAllConfigs(): Promise<number> {
  const rules = await dao.loadRules();
  await dao.clearVhostConfigs();

  let count = 0;
  for (const rule of rules) {
    if (!rule.enabled) continue;
    const content = generateVhostConfig(rule);
    await dao.writeVhostConfig(vhostFilename(rule.id), content);
    count++;
  }
  return count;
}

/* ---------- 规则 CRUD ---------- */

/** 获取全部规则 */
export async function listRules(): Promise<ProxyRule[]> {
  return dao.loadRules();
}

/** 获取单条规则 */
export async function getRule(id: string): Promise<ProxyRule> {
  const rules = await dao.loadRules();
  const rule = rules.find((r) => r.id === id);
  if (!rule) {
    throw AppError.notFound(`代理规则 [${id}]`);
  }
  return rule;
}

/** 创建规则 */
export async function createRule(
  input: CreateProxyRuleInput,
): Promise<ProxyRule> {
  validateDomain(input.domain);
  validateTarget(input.target);
  const rulePath = input.path ?? '/';
  validatePath(rulePath);

  const rules = await dao.loadRules();

  // 检查域名+路径唯一性
  const duplicate = rules.find(
    (r) => r.domain === input.domain && r.path === rulePath,
  );
  if (duplicate) {
    throw AppError.conflict(
      `域名 ${input.domain} 路径 ${rulePath} 已存在规则 [${duplicate.id}]`,
    );
  }

  const now = new Date().toISOString();
  const rule: ProxyRule = {
    id: randomUUID(),
    name: input.name,
    domain: input.domain,
    path: rulePath,
    target: input.target,
    websocket: input.websocket ?? false,
    https: input.https ?? false,
    accessLog: input.accessLog ?? true,
    enabled: input.enabled ?? true,
    createdAt: now,
    updatedAt: now,
  };

  rules.push(rule);
  await dao.saveRules(rules);

  // 生成该规则的 vhost 配置
  if (rule.enabled) {
    const content = generateVhostConfig(rule);
    await dao.writeVhostConfig(vhostFilename(rule.id), content);
  }

  return rule;
}

/** 更新规则 */
export async function updateRule(
  id: string,
  input: UpdateProxyRuleInput,
): Promise<ProxyRule> {
  const rules = await dao.loadRules();
  const idx = rules.findIndex((r) => r.id === id);
  if (idx === -1) {
    throw AppError.notFound(`代理规则 [${id}]`);
  }

  const existing = rules[idx]!;

  // 校验更新字段
  if (input.domain !== undefined) validateDomain(input.domain);
  if (input.target !== undefined) validateTarget(input.target);
  if (input.path !== undefined) validatePath(input.path);

  // 检查域名+路径唯一性（排除自身）
  const newDomain = input.domain ?? existing.domain;
  const newPath = input.path ?? existing.path;
  const duplicate = rules.find(
    (r) =>
      r.id !== id && r.domain === newDomain && r.path === newPath,
  );
  if (duplicate) {
    throw AppError.conflict(
      `域名 ${newDomain} 路径 ${newPath} 已存在规则 [${duplicate.id}]`,
    );
  }

  const updated: ProxyRule = {
    ...existing,
    name: input.name ?? existing.name,
    domain: newDomain,
    path: newPath,
    target: input.target ?? existing.target,
    websocket: input.websocket ?? existing.websocket,
    https: input.https ?? existing.https,
    accessLog: input.accessLog ?? existing.accessLog,
    enabled: input.enabled ?? existing.enabled,
    updatedAt: new Date().toISOString(),
  };

  rules[idx] = updated;
  await dao.saveRules(rules);

  // 更新 vhost 配置
  if (updated.enabled) {
    const content = generateVhostConfig(updated);
    await dao.writeVhostConfig(vhostFilename(updated.id), content);
  } else {
    await dao.removeVhostConfig(vhostFilename(updated.id));
  }

  return updated;
}

/** 删除规则 */
export async function deleteRule(id: string): Promise<{ deleted: string }> {
  const rules = await dao.loadRules();
  const idx = rules.findIndex((r) => r.id === id);
  if (idx === -1) {
    throw AppError.notFound(`代理规则 [${id}]`);
  }

  rules.splice(idx, 1);
  await dao.saveRules(rules);
  await dao.removeVhostConfig(vhostFilename(id));

  return { deleted: id };
}

/* ---------- nginx 重载 ---------- */

/**
 * 重新生成配置并重载 nginx
 * 使用 systemctl reload nginx（命令白名单内）
 */
export async function reloadNginx(): Promise<ReloadResult> {
  const configCount = await generateAllConfigs();

  try {
    await executeCommandStrict('systemctl', ['reload', 'nginx']);
    const now = new Date().toISOString();
    await dao.saveLastReload(now);
    return {
      success: true,
      message: `nginx 重载成功，已生成 ${configCount} 个 vhost 配置`,
      configCount,
    };
  } catch (err) {
    const msg =
      err instanceof AppError
        ? err.message
        : err instanceof Error
          ? err.message
          : String(err);
    return {
      success: false,
      message: `nginx 重载失败: ${msg}`,
      configCount,
    };
  }
}

/* ---------- 证书管理 ---------- */

/** 获取代理证书状态 */
export async function getCertInfo(): Promise<ProxyCertInfo> {
  const status: CertStatus = await getCertStatus(
    dao.CERT_PATH,
    dao.KEY_PATH,
  );
  return {
    installed: status.installed,
    certPath: status.certPath,
    keyPath: status.keyPath,
    info: status.info,
    error: status.error,
  };
}

/** 生成自签证书 */
export async function generateCert(
  input: GenerateCertInput,
): Promise<CertInfo> {
  if (!input.sans || input.sans.length === 0) {
    throw AppError.badRequest(
      'INVALID_SANS',
      'SAN 列表不能为空',
    );
  }

  return generateSelfSignedCert({
    certPath: dao.CERT_PATH,
    keyPath: dao.KEY_PATH,
    commonName: input.commonName ?? input.sans[0] ?? 'vibeos-proxy',
    sans: input.sans,
    days: input.days ?? 825,
    keySize: input.keySize ?? 2048,
  });
}

/* ---------- 状态 ---------- */

/** 获取代理模块状态 */
export async function getStatus(): Promise<ProxyStatus> {
  const rules = await dao.loadRules();
  const cert = await getCertStatus(dao.CERT_PATH, dao.KEY_PATH);
  const lastReload = await dao.loadLastReload();

  return {
    totalRules: rules.length,
    enabledRules: rules.filter((r) => r.enabled).length,
    certInstalled: cert.installed,
    configDir: dao.NGINX_VHOST_DIR,
    lastReload,
  };
}
